### ISSUE TITLE
Controllers - Views ( Country )

### ISSUE THREAD

**Issue by SebastianArielFlores** [MiltonLand/trabajo_practico_3#14]
* Index (to list all countries)
* Create (to create a new country)
* Edit (to modify and update a country)

**Comment by SebastianArielFlores** [comment]
**Index is DONE!**

**Comment by SebastianArielFlores** [comment]
**Create is DONE!**

**Comment by SebastianArielFlores** [comment]
**Edit is DONE!** :smiley:

**Comment by SebastianArielFlores** [comment]
Still could be improved visually and maybe changing the code... :thinking: 

# Still in progress... :construction:

**Comment by MiltonLand** [comment]
Done
