### ISSUE TITLE
Controllers - Views  ( Employee )

### ISSUE THREAD

**Issue by SebastianArielFlores** [MiltonLand/trabajo_practico_3#15]
* Index (to list all employees)
* Create (to create a new employee)
* Edit (to modify and update an employee)

**Comment by SebastianArielFlores** [comment]
**Index is DONE!** :+1:

**Comment by SebastianArielFlores** [comment]
**Create is DONE!** :grin:

**Comment by SebastianArielFlores** [comment]
**Delete is (simple) but DONE!** :grinning:

**Comment by SebastianArielFlores** [comment]
# Edit is still in development.. :construction: :construction_worker_man: :hammer_and_wrench:

**Comment by MiltonLand** [comment]
Done
