### ISSUE TITLE
Edit Web "Home":

### ISSUE THREAD

**Issue by SebastianArielFlores** [MiltonLand/trabajo_practico_3#4]
Remove the unused parts or edit the main Home of the web...

( "Getting started..." , "Get more libraries" ,"Web Hosting" and the "Learn more »" links should be removed )

Maybe add a presentation in the Home, with pictures or something to catch the eye of the visitor.

**Comment by MiltonLand** [comment]
Jaja eso de agregar una presentación está de más. Para eso ponemos memes en el index para hacerlo más divertido ajjaaa. Si lo hacemos va a ser lo último que se haga.

**Comment by SebastianArielFlores** [comment]
jajaja naa pero digo ponerle algo introductorio alguna imagen que diga que de que se trata... a ver si encuentro algo para dar una idea de lo que quise decir jeje

**Comment by SebastianArielFlores** [comment]
Algo así @MiltonLand 

[https://www.kronos.co.uk/sites/default/files/styles/card_mobile/public/images/reference/resource-ref-16264_2.jpg?itok=tLcW7X9a
![image](https://user-images.githubusercontent.com/34099887/33918967-f4603fa4-df94-11e7-8039-48ea764627ed.png)
](url) 

O así....

[https://www.bankofinternet.com/portals/bofiusa/Images/blog/bofi-employee-benefits.jpg
![image](https://user-images.githubusercontent.com/34099887/33918974-fd927a56-df94-11e7-874f-a7f92e0d3117.png)
](url)

Igual sería algo para darle un **retoque final** no es tan importante...

**Comment by SebastianArielFlores** [comment]
Well... I think is **_DONE_** :thinking:
