### ISSUE TITLE
SqlException: Conversion failed when converting the nvarchar value 'mañana' to data type int.

### ISSUE THREAD

**Issue by MiltonLand** [MiltonLand/trabajo_practico_3#6]
No puedo ingresar el campo shift a la base de datos porque hay un conflicto entre esto...

CREATE TABLE [dbo].[Employees] (
  **[Shift]      INT           NOT NULL**
);

y esto...

public partial class Employees
    {
        [StringLength(50)]
       **public string Shift { get; set; }**
    }

Me tira conflicto porque uno es un entero y otro es string.

**Comment by SebastianArielFlores** [comment]
Mmmm que raro che. Todavía no lo pude revisar, pudiste solucionarlo @MiltonLand???
Después lo vemos sino...

**Comment by SebastianArielFlores** [comment]
Fixed!
